## Упражнения по библиотеке Numpy

In [3]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [67]:
a = np.arange(15)
a[(a > 3) & (a < 8)] *= -1
print(a)


[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14]


**2.** Заменить максимальный элемент случайного массива на 0

In [70]:
a = np.random.randint(0,10,20)
a[a.argmax()] = 0
print(a)

[5 1 4 0 5 2 2 9 6 3 7 0 5 2 6 5 9 9 3 0]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [79]:
a=[[1,3,5,7],[1,2,3,4],[1,4,7,10]]
arr = np.asarray(a)
print(arr)
shp = map(len, arr)
res = np.indices(shp, dtype=int)
res = res.reshape(len(arr), -1).T
for n, arr in enumerate(arr):
   res[:, n] = arr[n][res[:, n]]
print(res)


[[ 1  3  5  7]
 [ 1  2  3  4]
 [ 1  4  7 10]]
[[ 1  1  1]
 [ 1  1  4]
 [ 1  1  7]
 [ 1  1 10]
 [ 1  2  1]
 [ 1  2  4]
 [ 1  2  7]
 [ 1  2 10]
 [ 1  3  1]
 [ 1  3  4]
 [ 1  3  7]
 [ 1  3 10]
 [ 1  4  1]
 [ 1  4  4]
 [ 1  4  7]
 [ 1  4 10]
 [ 3  1  1]
 [ 3  1  4]
 [ 3  1  7]
 [ 3  1 10]
 [ 3  2  1]
 [ 3  2  4]
 [ 3  2  7]
 [ 3  2 10]
 [ 3  3  1]
 [ 3  3  4]
 [ 3  3  7]
 [ 3  3 10]
 [ 3  4  1]
 [ 3  4  4]
 [ 3  4  7]
 [ 3  4 10]
 [ 5  1  1]
 [ 5  1  4]
 [ 5  1  7]
 [ 5  1 10]
 [ 5  2  1]
 [ 5  2  4]
 [ 5  2  7]
 [ 5  2 10]
 [ 5  3  1]
 [ 5  3  4]
 [ 5  3  7]
 [ 5  3 10]
 [ 5  4  1]
 [ 5  4  4]
 [ 5  4  7]
 [ 5  4 10]
 [ 7  1  1]
 [ 7  1  4]
 [ 7  1  7]
 [ 7  1 10]
 [ 7  2  1]
 [ 7  2  4]
 [ 7  2  7]
 [ 7  2 10]
 [ 7  3  1]
 [ 7  3  4]
 [ 7  3  7]
 [ 7  3 10]
 [ 7  4  1]
 [ 7  4  4]
 [ 7  4  7]
 [ 7  4 10]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [87]:
a=np.random.randint(0,10,(8,3))
print(a)
b=np.random.randint(0,10,(2,2))
print(b)
c=(a[...,np.newaxis,np.newaxis]==b)
res = (c.sum(axis=(1,2,3)) >= b.shape[1]).nonzero()[0]
print(res)

[[5 6 9]
 [3 1 0]
 [8 2 0]
 [9 4 1]
 [4 9 2]
 [2 1 6]
 [7 8 7]
 [4 9 7]]
[[6 2]
 [4 0]]
[2 4 5]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [99]:
a = np.random.randint(0,2,(10,3))
b = np.logical_and.reduce(a[:,1:] == a[:,:-1], axis=1)
res = a[~b]
print(a)
print(res)

[[1 1 1]
 [0 1 1]
 [0 1 1]
 [1 1 1]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [1 0 1]
 [1 0 0]
 [0 1 0]]
[[0 1 1]
 [0 1 1]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [1 0 1]
 [1 0 0]
 [0 1 0]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [4]:
a = np.random.randint(0, 2, (6,3))
print(a)
b = np.ascontiguousarray(a).view(np.dtype((np.void,a.dtype.itemsize*a.shape[1])))
_, c = np.unique(b, return_index=True)
res = a[c]
print(res)

[[1 0 0]
 [1 1 1]
 [0 1 1]
 [1 0 0]
 [0 0 1]
 [0 0 1]]
[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 1 1]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [4]:
x = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
print(np.prod(np.diag(x)[np.diag(x)!=0]))
print()
a=1
for i in range(len(x)):
    for j in range(len(x[i])):
        if i == j:
            #print('a')
            #print (x[i][j])
            if x[i][j] != 0:
                #print('b')
                #print (x[i][j])
                a= a*(x[i][j])
                #print(a)
print('res')                
print(a)

3

res
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [5]:
# your code
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2]) 
print(np.isin(x,y).all())

x = ([1, 2, 2, 4])
y = ([4, 2, 1, 2])
for i in x:
    y.remove(i)
if y == []:
    a = 'true'
else:
    a = 'false'

print(a)

True
true


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [6]:
# your code
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(np.max(x[1:][(x==0)[:-1]]))

x =([6, 2, 0, 3, 0, 0, 5, 7, 0])
a = 0
for i in range(1, len(x)):
    if x[i-1] == 0:
        if x[i] > a:
            a = x[i]
print(a)

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [83]:
# your code
x = np.array([2, 2, 2, 3, 3, 3, 5]) 
a = x.shape[0]
if a != 0:
    loc_run_start = np.empty(a, dtype=bool)
    run_starts = np.nonzero(loc_run_start)[0]
    run_values = x[loc_run_start]
    run_lengths = np.diff(np.append(run_starts, a))
    print(run_values)
    print(run_lengths)

x = ([2, 2, 2, 3, 3, 3, 5])
count = 0
b=[]
c=[]
for i in range(0, len(x)):
    if i == 0:
        count = 1
        b.append(x[i])
        #print(x[i], count)
    else:
        if x[i]== x[i-1]:
            count = count +1
            #print(x[i], count)
        else:
            c.append(count)
            count = 1
            b.append(x[i])
            #print(x[i], count)
            if i == len(x)-1:
                c.append(count)
print(b)
print(c)
        


[2 3 5]
[3 3 1]
2 1
2 2
2 3
3 1
3 2
3 3
5 1
[2, 3, 5]
[3, 3, 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [92]:
# your code
import scipy.spatial.distance

a = np.array([[1,1,1]])
b = np.random.rand(10,3)
dist = np.linalg.norm(a - b, axis = 1)
print(dist)

distances = scipy.spatial.distance.cdist(b, a, metric='euclidean')
print(distances)

[0.75948655 0.76052219 0.39331522 1.02956514 1.10270003 0.62727024
 1.15665164 0.657766   1.26333168 1.09234984]
[[0.75948655]
 [0.76052219]
 [0.39331522]
 [1.02956514]
 [1.10270003]
 [0.62727024]
 [1.15665164]
 [0.657766  ]
 [1.26333168]
 [1.09234984]]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [77]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [94]:
calorie_stats = np.loadtxt("D:/Prog/Innowise/pandas_numpy_tasks/data/cereal.csv", delimiter=",") #захардкодил путь
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [96]:
average_calories = np.mean(calorie_stats)
print(average_calories)
calories_high = average_calories - 60
print(calories_high)

106.88311688311688
46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [97]:
# your code
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [98]:
# your code
median_calories = np.median(calorie_stats_sorted)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [113]:
# your code
nth_percentile = np.percentile(calorie_stats_sorted,3.29)
print(nth_percentile)

60.007999999999996


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [114]:
# your code
more_calories = len(calorie_stats_sorted[calorie_stats_sorted>60])/len(calorie_stats_sorted)*100
print(more_calories)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [120]:
# your code
calorie_std = np.std(calorie_stats_sorted)
print(calorie_std)
calorie_std2 = np.std(calorie_stats)
print(calorie_std2)


19.35718533390827
19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
# your code
#во-первых, эти данные прекоассно показывают, что продукция нашей компании - на много менее колорийная, чем у конкурентов
#во-вторых, мы можем понять какой процент продукции и какие бренды конкурентов могут конкурировать (пардон за тавтологию)
#с нашим новым продуктом.
